# Lesson 3 – Pandas and Exploratory Data Analysis (EDA)

**Author:** Alexandre Nordin  

## Goals
- Introduce Pandas for tabular data analysis
- Load and inspect real datasets
- Perform basic exploratory data analysis

In [1]:
import pandas as pd

### Creating a simple exemple of data base

In [2]:
data = {
    "month":["jan", "feb", "mar", "apr", "may"],
    "sales":[12000, 15000, 18000, 17000, 16000],
    "costs":[5000, 5500, 4500, 6500, 6000]
}
df =pd.DataFrame(data)
df

  month  sales  costs
0   jan  12000   5000
1   feb  15000   5500
2   mar  18000   4500
3   apr  17000   6500
4   may  16000   6000

### First data reading (Basic EDA)
## EDA is very important to data scientist kwon the data and data structure
## Based on this onformation, the data scientist begins to clean and optimize the data, for this there are many different techniques for this, we will study some of them later in the course.

In [ ]:
## Print the data
df.head()
## Print data informations (data types, total of lines, total of columns and statistics)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   month   5 non-null      str
 1   sales   5 non-null      int64
 2   costs   5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 252.0 bytes

In [5]:
## Creating new columns
## Profit column

df["profit"] = df["sales"] - df["costs"]
df

  month  sales  costs  profit
0   jan  12000   5000    7000
1   feb  15000   5500    9500
2   mar  18000   4500   13500
3   apr  17000   6500   10500
4   may  16000   6000   10000

### Here we start to know the power of Pandas
## Get the metrics is very simple
## See the diference to calss 1 and 2

In [10]:
df["profit"].sum()
df["profit"].mean()
df["profit"].max()
df["profit"].min()

np.int64(7000)

In [11]:
## Analyses with filter (analytical thinking)
## What monyhs was over the mean

df[df["profit"]>df["profit"].mean()]

  month  sales  costs  profit
2   mar  18000   4500   13500
3   apr  17000   6500   10500

### Exploratory Data Analysis Insights

Using Pandas made the analysis more concise and expressive.
By organizing data into a DataFrame, it became easier to compute metrics,
identify high-performing months, and compare results visually and logically.

This reinforces the importance of structured data representation in Data Science.

### Lesson exercise
## create a column "margin"
## get the major, minimal and average
## filter thwe months over de average

In [ ]:
# Creating nem margin colun
df["margin"] = df["profit"] / df["sales"] * 100
df

  month  sales  costs  profit     margin
0   jan  12000   5000    7000  58.333333
1   feb  15000   5500    9500  63.333333
2   mar  18000   4500   13500  75.000000
3   apr  17000   6500   10500  61.764706
4   may  16000   6000   10000  62.500000

In [ ]:
# Get metrics
df["margin"].max()
df["margin"].min()
df["margin"].mean()

np.float64(64.18627450980392)

In [17]:
# Filter the months over the average

df[df["margin"] > df["margin"].mean()]

  month  sales  costs  profit  margin
2   mar  18000   4500   13500    75.0